### ISSUE TITLE
Is it a good idea to input multiple RNAseq assembler results?

### ISSUE THREAD

**Issue by xiekunwhy** [EVidenceModeler/EVidenceModeler#48]
Hi,

I used trinity+gmap, stringtie, scallop to assemble my RNAseq datas, is it a good idea to input multiple RNAseq assembler results? Or use one of them is enough?

Best,
Kun

**Comment by brianjohnhaas** [comment]
As long as the results from each look good, it usually shouldn't hurt
to leverage them all.  If one gets it right where the others fail, EVM
will be able to leverage the one that got it right.

On Thu, Feb 24, 2022 at 5:29 AM xiekunwhy ***@***.***> wrote:
>
> Hi,
>
> I used trinity+gmap, stringtie, scallop to assemble my RNAseq datas, is it a good idea to input multiple RNAseq assembler results? Or use one of them is enough?
>
> Best,
> Kun
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by xiekunwhy** [comment]
I see, thank you for your reply.
