### ISSUE TITLE
Many incomplete gene model in evm results even all input prediction are complete.

### ISSUE THREAD

**Issue by xiekunwhy** [EVidenceModeler/EVidenceModeler#49]
Hi,

I found many (~1.8k, 1/10) incomplete (lack of start or stop codon) gene model in evm results even all input prediction are complete. Why and how to avoid?

Best,
Kun

**Comment by xiekunwhy** [comment]
I found answer in other issue.

**Comment by CrawlingSponge** [comment]
> I found answer in other issue.

which issue？

**Comment by xiekunwhy** [comment]
https://github.com/EVidenceModeler/EVidenceModeler/issues/47

**Comment by CrawlingSponge** [comment]
> #47

still not find the answer...
